apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
    pkg.ndd.yndd.io/controller: admin
  name: controller-manager-metrics-service
  namespace: ndd-system
spec:
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: https
  selector:
    control-plane: controller-manager
    pkg.ndd.yndd.io/controller: admin
