apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations: {}
  creationTimestamp: null
  name: admin-controller-controller-role
rules:
- apiGroups:
  - '*'
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
- apiGroups:
  - admin.yndd.io
  resources:
  - tenants
  - tenants/status
  verbs:
  - get
  - list
  - watch
  - update
  - patch
  - create
  - delete
