apiVersion: v1
kind: Service
metadata:
  annotations: {}
  creationTimestamp: null
  labels:
    fn.kptgen.dev/metrics: admin-controller
  name: admin-controller-metrics-svc
  namespace: ndd-system
spec:
  ports:
  - name: grpc
    port: 8443
    protocol: TCP
    targetPort: 443
  selector:
    fn.kptgen.dev/metrics: admin-controller
status:
  loadBalancer: {}
