apiVersion: admin.yndd.io/v1alpha1
kind: Tenant
metadata:
  name: tenant2
  namespace: ndd-system
spec:
  properties:
    organizationRef: nokia
    region: eu-west
    availabilityZone: az1
    repositoryRef: mgmt-admin
    packagerefs:
      - repository: yndd-mgmt-app-packages
        packageName: topology-app
        revision: main
      - repository: yndd-mgmt-app-packages
        packageName: label-app
        revision: main
    clusters:
    - clusterRef: eu-west-az1-cluster1
      repositoryRef:
        group1: eu-west-az1-cluster1-group1
        group2: eu-west-az1-cluster1-group2

    