apiVersion: fn.kptgen.dev/v1alpha1
kind: Config
metadata:
  name: profiler
  annotations:
    config.kubernetes.io/local-config: "true"
  namespace: ndd-system
spec:
  selector:
    kind: Deployment
    name: controller
    containerName: controller
  volume: true