apiVersion: fn.kpt.dev/v1alpha1
kind: SetLabels
metadata:
  name: label-fn-config
  annotations:
    config.kubernetes.io/local-config: "true"
  namespace: ndd-system
  labels:
    pkg.ndd.yndd.io/controller: admin
labels:
  pkg.ndd.yndd.io/controller: admin
additionalLabelFields:
  - kind: ServiceMonitor
    group: monitoring.coreos.com
    version: v1
    create: true
    path: spec/selector/matchLabels
