apiVersion: v1
kind: ConfigMap
metadata:
  name: kptfile.kpt.dev
  annotations:
    config.kubernetes.io/local-config: "true"
  namespace: ndd-system
  labels:
    pkg.ndd.yndd.io/controller: admin
data:
  name: example
